version: '3.8'

services:
  db:
    image: postgres:15
    container_name: weather_data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./ddl/weatherdata.sql:/docker-entrypoint-initdb.d/init.sql
